include(InstallRequiredSystemLibraries)

SET(CPACK_GENERATOR NSIS)
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "PerkLab Ultrasound Library")
SET(CPACK_PACKAGE_VENDOR "Queen's University")
# SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/ReadMe.txt")
# SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/Copyright.txt")
SET(CPACK_PACKAGE_VERSION_MAJOR ${PLUS_VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${PLUS_VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${PLUS_VERSION_PATCH})
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "PLUS_${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}.${PLUS_REVISION}")
SET(CPACK_PACKAGE_FILE_NAME "Release/${CPACK_PACKAGE_INSTALL_DIRECTORY}" )

set(CPACK_INSTALL_CMAKE_PROJECTS
  "${PLUS_BINARY_DIR};PLUS;ALL;/")
  
IF(DEFINED VTK_DIR)
  SET(CPACK_INSTALL_CMAKE_PROJECTS "${CPACK_INSTALL_CMAKE_PROJECTS};${VTK_DIR};VTK;RuntimeLibraries;/")
ELSE(DEFINED VTK_DIR)
    MESSAGE(WARNING "Unable to set VTK_DIR for package generation!")
ENDIF(DEFINED VTK_DIR)

IF(DEFINED ITK_DIR)
	SET(ITK_USE_REVIEW OFF)
	SET(CPACK_INSTALL_CMAKE_PROJECTS "${CPACK_INSTALL_CMAKE_PROJECTS};${ITK_DIR};ITK;RuntimeLibraries;/")
ELSE(DEFINED ITK_DIR)
    MESSAGE(WARNING "Unable to set ITK_DIR for package generation!")
ENDIF(DEFINED ITK_DIR)

IF ( PLUS_USE_OpenIGTLink )
	IF(DEFINED OpenIGTLink_DIR)
		SET(CPACK_INSTALL_CMAKE_PROJECTS "${CPACK_INSTALL_CMAKE_PROJECTS};${OpenIGTLink_DIR};OpenIGTLink;RuntimeLibraries;/")
	ELSE(DEFINED OpenIGTLink_DIR)
		MESSAGE(WARNING "Unable to set OpenIGTLink_DIR for package generation!")
	ENDIF(DEFINED OpenIGTLink_DIR)
ENDIF (PLUS_USE_OpenIGTLink)

#-----------------------------------------------------------------------------
# Installation vars.
# PLUS_INSTALL_BIN_DIR          - binary dir (executables)
# PLUS_INSTALL_LIB_DIR          - library dir (libs)
# PLUS_INSTALL_DATA_DIR         - share dir (say, examples, data, etc)
# PLUS_INSTALL_CONFIG_DIR       - config dir (configuration files)
# PLUS_INSTALL_GNUPLOT_DIR      - gnuplot dir (gnuplot binary files)
# PLUS_INSTALL_SCRIPTS_DIR      - scripts dir (gnuplot script files)
# PLUS_INSTALL_INCLUDE_DIR      - include dir (headers)
# PLUS_INSTALL_PACKAGE_DIR      - package/export configuration files
# PLUS_INSTALL_NO_DEVELOPMENT   - do not install development files
# PLUS_INSTALL_NO_RUNTIME       - do not install runtime files
# PLUS_INSTALL_NO_DOCUMENTATION - do not install documentation files
# Applications
# RuntimeLibraries
# Development

IF(NOT PLUS_INSTALL_BIN_DIR)
  SET(PLUS_INSTALL_BIN_DIR "bin")
ENDIF(NOT PLUS_INSTALL_BIN_DIR)

IF(NOT PLUS_INSTALL_LIB_DIR)
  SET(PLUS_INSTALL_LIB_DIR "lib")
ENDIF(NOT PLUS_INSTALL_LIB_DIR)

IF(NOT PLUS_INSTALL_DATA_DIR)
  SET(PLUS_INSTALL_DATA_DIR "data")
ENDIF(NOT PLUS_INSTALL_DATA_DIR)

IF(NOT PLUS_INSTALL_CONFIG_DIR)
  SET(PLUS_INSTALL_CONFIG_DIR "config")
ENDIF(NOT PLUS_INSTALL_CONFIG_DIR)

IF(NOT PLUS_INSTALL_GNUPLOT_DIR)
  SET(PLUS_INSTALL_GNUPLOT_DIR "gnuplot")
ENDIF(NOT PLUS_INSTALL_GNUPLOT_DIR)

IF(NOT PLUS_INSTALL_SCRIPTS_DIR)
  SET(PLUS_INSTALL_SCRIPTS_DIR "scripts")
ENDIF(NOT PLUS_INSTALL_SCRIPTS_DIR)

IF(NOT PLUS_INSTALL_INCLUDE_DIR)
  SET(PLUS_INSTALL_INCLUDE_DIR "include")
ENDIF(NOT PLUS_INSTALL_INCLUDE_DIR)

IF(NOT PLUS_INSTALL_NO_DOCUMENTATION)
  SET(PLUS_INSTALL_NO_DOCUMENTATION 0)
ENDIF(NOT PLUS_INSTALL_NO_DOCUMENTATION)

#SET(CPACK_COMPONENTS_ALL Applications Development RuntimeLibraries)

# SET(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Applications")
# SET(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "Libraries")
# SET(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "C++ Headers")

# SET(CPACK_COMPONENT_APPLICATIONS_GROUP "Runtime")
# SET(CPACK_COMPONENT_LIBRARIES_GROUP "Development")
# SET(CPACK_COMPONENT_HEADERS_GROUP "Development")

INCLUDE(CPack)