# Find the Optimet Smart 32 SDK
# http://www.optimet.com/smart32-sdk.php
# This module defines:
# OPTIMETSMART32SDK_FOUND
# OPTIMETSMART32SDK_INCLUDE_DIR
# OPTIMETSMART32SDK_BINARY_DIR
# OPTIMETSMART32SDK_LIBRARY

SET(OPTIMETSMART32SDK_PATH_HINTS 
  "C:/Optimet/Ethernet Probe SDK/Ethernet Probe SDK/Code Samples"
)

FIND_PATH(OPTIMETSMART32SDK_INCLUDE_DIR
  NAMES "Smart32Interface.h"
  PATH_SUFFIXES "Include"
  PATHS "${OPTIMETSMART32SDK_PATH_HINTS}"
  DOC "Include directory of the Optimet Smart 32 SDK"
)

# 64-bit
FIND_PATH(OPTIMETSMART32SDK_BINARY_DIR
  NAMES "Smart32.dll" "NewProbeDialog.dll"
  PATH_SUFFIXES "Bin"
  PATHS "${OPTIMETSMART32SDK_PATH_HINTS}"
  DOC "Directory containing the Smart32.dll, NewProbeDialog.dll and Fifo.dll of the Optimet Smart 32 SDK"
  NO_DEFAULT_PATH # Avoids finding installed DLLs in the system folders
)

FIND_LIBRARY(OPTIMETSMART32SDK_LIBRARY
  NAMES Smart32.lib
  PATH_SUFFIXES "Lib"
  PATHS "${OPTIMETSMART32SDK_PATH_HINTS}"
  DOC "Path to the Smart32.lib for the Optimet Smart 32 SDK"
)

# handle the QUIETLY and REQUIRED arguments and set OPTIMETSMART32SDK_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPTIMETSMART32SDK DEFAULT_MSG OPTIMETSMART32SDK_INCLUDE_DIR OPTIMETSMART32SDK_BINARY_DIR OPTIMETSMART32SDK_LIBRARY)

SET(OPTIMETSMART32SDK_FOUND ${OPTIMETSMART32SDK_FOUND}) 
IF(OPTIMETSMART32SDK_FOUND)
  SET( OPTIMETSMART32SDK_INCLUDE_DIR ${OPTIMETSMART32SDK_INCLUDE_DIR} )
  SET( OPTIMETSMART32SDK_BINARY_DIR ${OPTIMETSMART32SDK_BINARY_DIR} )
  SET( OPTIMETSMART32SDK_LIBRARY ${OPTIMETSMART32SDK_LIBRARY} )
ENDIF()
