#!/bin/bash

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}

result=`awk '/(addresses|re|refs|references|see|new|accepted|test|closed|invalid|fix|fixes|close|closed|closes|untest|reassign|reopen|accept) \#[1-9][0-9]*/ {print}' $1`

if [ -z "$result" ]
then
	echo >&2 Commit message must reference a ticket.
	echo >&2 Please use \<action\> \#\<ticketNumber\> in your commit message.
	exit 1
fi

exit 0