# Find the StealthLink2.0 Libraries
# This module defines
# STEALTHLINK2_INCLUDE_DIRS - STEALTHLINK header files 
# STEALTHLINK2_STEALTHLINK_STATIC_LIBRARY  - STEALTHLINK static library
# STEALTHLINK2_STEALTHLINKD_STATIC_LIBRARY - STEALTHLINK static library with debug info
# STEALTHLINK2_STEALTHLINK_SHARED_LIBRARY  - STEALTHLINK shared library
# STEALTHLINK2_STEALTHLINKD_SHARED_LIBRARY - STEALTHLINK shared library with debug info
#

message("HELLO")
SET( STEALTHLINK_PATH_HINTS 
    ../StealthLink-2.0.1
    ../PLTools/StealthLink-2.0.1
    ../../PLTools/StealthLink-2.0.1
    ../trunk/PLTools/StealthLink-2.0.1
    ${CMAKE_CURRENT_BINARY_DIR}/StealthLink-2.0.1
    )
	
IF ( NOT ${CMAKE_GENERATOR} MATCHES "Visual Studio 10" )
		MESSAGE(FATAL_ERROR "error: StealthLink can only be built using Visual Studio 2010")
ENDIF ( NOT ${CMAKE_GENERATOR} MATCHES "Visual Studio 10" )

SET (PLATFORM_SUFFIX "Win32")
IF (CMAKE_HOST_WIN32 AND CMAKE_CL_64)
	SET( PLATFORM_SUFFIX "x64")
ENDIF (CMAKE_HOST_WIN32 AND CMAKE_CL_64)

find_path (STEALTHLINK2_INCLUDE_DIRS
           NAMES "StealthLink/Stealthlink.h"
		   PATHS ${STEALTHLINK_PATH_HINTS} 
           DOC "Include directory, i.e. parent directory of directory \"StealthLink\"")

FIND_LIBRARY (STEALTHLINK2_STEALTHLINK_STATIC_LIBRARY
			  NAMES StealthLink
			  PATH_SUFFIXES /windows/${PLATFORM_SUFFIX}/Release 
			  PATHS ${STEALTHLINK_PATH_HINTS}
			  )
FIND_LIBRARY (STEALTHLINK2_STEALTHLINKD_STATIC_LIBRARY
			  NAMES StealthLink
			  PATH_SUFFIXES /windows/${PLATFORM_SUFFIX}/Debug 
			  PATHS ${STEALTHLINK_PATH_HINTS}
			  )
FIND_FILE (STEALTHLINK2_STEALTHLINK_SHARED_LIBRARY
    	   NAMES StealthLink${CMAKE_SHARED_LIBRARY_SUFFIX}
		   PATH_SUFFIXES /windows/${PLATFORM_SUFFIX}/Release 
		   PATHS ${STEALTHLINK_PATH_HINTS}
		   )
FIND_FILE (STEALTHLINK2_STEALTHLINKD_SHARED_LIBRARY
		   NAMES StealthLink${CMAKE_SHARED_LIBRARY_SUFFIX}
		   PATH_SUFFIXES /windows/${PLATFORM_SUFFIX}/Debug
		   PATHS ${STEALTHLINK_PATH_HINTS}
		   )				  

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STEALTHLINK DEFAULT_MSG  
  STEALTHLINK2_INCLUDE_DIRS  
  STEALTHLINK2_STEALTHLINK_STATIC_LIBRARY
  STEALTHLINK2_STEALTHLINK_SHARED_LIBRARY
  STEALTHLINK2_STEALTHLINKD_STATIC_LIBRARY
  STEALTHLINK2_STEALTHLINKD_SHARED_LIBRARY
  )

