MACRO(PlusLibInstallLibrary _target_name _variable_root)
  INSTALL(TARGETS ${_target_name} EXPORT PlusLib
    RUNTIME DESTINATION "${PLUSLIB_BINARY_INSTALL}" CONFIGURATIONS Release COMPONENT RuntimeLibraries
    LIBRARY DESTINATION "${PLUSLIB_LIBRARY_INSTALL}" CONFIGURATIONS Release COMPONENT RuntimeLibraries
    ARCHIVE DESTINATION "${PLUSLIB_ARCHIVE_INSTALL}" CONFIGURATIONS Release COMPONENT Development
    )
  INSTALL(FILES ${${_variable_root}_HDRS}
    DESTINATION "${PLUSLIB_INCLUDE_INSTALL}" COMPONENT Development
    )
  GET_TARGET_PROPERTY(_library_type ${_target_name} TYPE)
  IF(${_library_type} STREQUAL SHARED_LIBRARY AND MSVC)
    INSTALL(FILES "$<TARGET_PDB_FILE:${_target_name}>" OPTIONAL
      DESTINATION "${PLUSLIB_BINARY_INSTALL}" COMPONENT RuntimeLibraries
      )
  ENDIF()
ENDMACRO()